# Generated by Django 4.0.1 on 2022-01-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[

                ('empid', models.CharField(blank=True, default='', max_length=500)),
                ('password', models.CharField(blank=True, default='', max_length=500)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('dept', models.CharField(blank=True, default='', max_length=500)),
                ('extension', models.CharField(blank=True, default='', max_length=100)),
                ('mobile', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
