# Generated by Django 4.0.1 on 2022-01-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='dept',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
