# Generated by Django 4.0.1 on 2022-01-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0002_alter_admin_dept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
    ]
